#!/usr/bin/env bash

cd "$(dirname "$0")/.."
export DOTFILES_ROOT=$(pwd -P)
DOTFILES_SOURCES=$(find . -name "*symlink" -type f -exec ls {} \;)
BASH_SOURCES=$(find . -name "*.sh" -type f -exec ls {} \;)

echo ''

set -e

printf "Setting up bin files...\n"
if [ ! -d "$DOTFILES_ROOT/bin" ]; then
  ln -s $DOTFILES_ROOT/bin ~/bin
  printf "bin files installed successfully\n"
else
  printf "bin files already installed\n"
fi

printf "running bash install scripts...\n"
for file_name in $BASH_SOURCES; do
  title=`grep '\# title\: ' $file_name | sed -e 's/# title: //g'`
  printf "→ installing $title ($file_name)...\n"
  sh $file_name
done

printf "symlinking dotfiles...\n"
for file_name in $DOTFILES_SOURCES; do
  source_location=$DOTFILES_ROOT/`echo $file_name | sed -e 's/\.\///g'`
  new_location=~/`echo $file_name | sed -e 's/\.\///g' -e 's/\.symlink//g' -e 's/^.*\//./g'`

  if [ ! -f $new_location ]; then
    ln -s $source_location $new_location
    printf "→ done symlinking $new_location...\n"
  else
    printf "→ skipping symlink for $new_location (already exists)...\n"
  fi
done
