#!/usr/bin/env bash

cd "$(dirname "$0")/.."
DOTFILES_ROOT=$(pwd -P)

set -e

echo ''

printf "Setting up homebrew...\n"
brew tap Homebrew/bundle
brew bundle --file="$DOTFILES_ROOT/Brewfile"

printf "Setting up bin files...\n"
if [ ! -d "$DOTFILES_ROOT/bin" ]; then
  ln -s $DOTFILES_ROOT/bin ~/bin
  printf "bin files installed successfully\n"
else
  printf "bin files already installed\n"
fi

printf "installing osx software updates...\n"
./osx/install.sh

printf "installing osx defaults...\n"
./osx/set-defaults.sh

printf "symlinking dotfiles...\n"
DOTFILES_SOURCES=$(find . -name "*symlink" -type f -exec ls {} \;)

for file_name in $DOTFILES_SOURCES; do
  source_location=`echo $file_name | sed -e 's/\.\///g'`
  new_location=~/`echo $source_location | sed -e 's/\.symlink//g' -e 's/^.*\//./g'`

  if [ ! -f $new_location ]; then
    ln -s $source_location $new_location
    printf "done symlinking $new_location...\n"
  else
    printf "skip symlinking $new_location (already exists)...\n"
  fi
done
