#!/usr/bin/env bash

cd "$(dirname "$0")/.."
export DOTFILES_ROOT=$(pwd -P)
DOTFILES_SOURCES=$(find . -name "*symlink" -type f -exec ls {} \;)
BASH_SOURCES=$(find . -name "*.sh" -type f -exec ls {} \;)

echo ''

info () {
  echo -e "\e[36m$1\e[0m"
}

error () {
  echo -e "\e[31m$1\e[0m"
}

success () {
  echo -e "\e[32m$1\e[0m"
}

warn () {
  echo -e "\e[33m$1\e[0m"
}


set -e

info "Setting up bin files..."
if [ ! -h ~/bin ]; then
  ln -s $DOTFILES_ROOT/bin $HOME
  success "→ bin files installed successfully"
else
  warn "→ bin files already installed"
fi

info "Running bash install scripts..."
for file_name in $BASH_SOURCES; do
  title=`grep '\# title\: ' $file_name | sed -e 's/# title: //g'`
  info "Installing $title ($file_name)..."
  sh $file_name #> /dev/null
  if [ $? -eq 0 ]; then
    success "→ $title installed successfully"
  else
    error "→ $title install failed"
  fi
done

info "Symlinking dotfiles..."
for file_name in $DOTFILES_SOURCES; do
  source_location=$DOTFILES_ROOT/`echo $file_name | sed -e 's/\.\///g'`
  new_location=~/`echo $file_name | sed -e 's/\.\///g' -e 's/\.symlink//g' -e 's/^.*\//./g'`

  if [ ! -f $new_location ]; then
    ln -s $source_location $new_location
    success "→ done symlinking $new_location..."
  else
    warn "→ skipping symlink for $new_location (already exists)..."
  fi
done
