#!/usr/bin/env bash

function __wt_root() {
    git rev-parse --path-format=absolute --git-common-dir
}

function __wt_after() {
    local afterhook="$(__wt_root)/.worktree-after"
    if [[ -f "$afterhook" ]]; then
        echo "Running afterhook"
        sh "$afterhook"
    fi
}

function new-worktree() {
    local user=$(whoami)
    local name="$1"

    if [[ -z "$name" ]]; then
        read -p "Enter worktree name: " name
    fi

    if [[ -z "$name" ]]; then
        echo "Name is required."
        return
    fi

    cd $(__wt_root)
    git fetch origin main
    git worktree add "$user/$name" -B "$user/$name" main
    cd "$user/$name"
    __wt_after
}

function list-worktree() {
    git worktree list | fzf | awk '{print $1}'
}

function switch-worktree() {
    cd $(list-worktree)
}

function remove-worktree() {
    local tree=$(list-worktree)

    cd $(__wt_root)
    git worktree remove "$tree"
}

function prune-merged-branches(){
    git checkout -q main && \
        git for-each-ref refs/heads/ "--format=%(refname:short)" | \
        while read branch; do \
            mergeBase=$(git merge-base main $branch) && \
            [[ $(git cherry main $(git commit-tree $(git rev-parse "$branch^{tree}") -p $mergeBase -m _)) == "-"* ]] && \
            git branch -D $branch;
        done
}
