[username]
disabled = false

[hostname]
disabled = false

[shlvl]
disabled = true

[kubernetes]
disabled = true

[directory]
disabled = false

[vcsh]
disabled = true

[git_branch]
disabled = false

[git_commit]
disabled = false

[git_state]
disabled = false

[git_metrics]
disabled = true

[git_status]
disabled = false

[hg_branch]
disabled = true

[docker_context]
disabled = true

[package]
disabled = true

[cmake]
disabled = true

[dart]
disabled = true

[deno]
disabled = true

[dotnet]
disabled = true

[elixir]
disabled = true

[elm]
disabled = true

[erlang]
disabled = true

[golang]
disabled = false

[helm]
disabled = true

[java]
disabled = true

[julia]
disabled = true

[kotlin]
disabled = false

[nim]
disabled = true

[nodejs]
disabled = true
detect_extensions = []
detect_folders = []
detect_files = ['.nvmrc']

[ocaml]
disabled = true

[perl]
disabled = true

[php]
disabled = false

[purescript]
disabled = true

[python]
disabled = true

[red]
disabled = true

[ruby]
disabled = false

[rust]
disabled = true

[scala]
disabled = true

[swift]
disabled = true

[terraform]
disabled = true

[vlang]
disabled = true

[vagrant]
disabled = true

[zig]
disabled = true

[nix_shell]
disabled = true

[conda]
disabled = true

[memory_usage]
disabled = true

[aws]
disabled = true

[gcloud]
disabled = true

[openstack]
disabled = true

[env_var]
disabled = true

[crystal]
disabled = true

[cmd_duration]
disabled = true

[line_break]
disabled = false

[lua]
disabled = true

[jobs]
disabled = true

[battery]
disabled = true

[time]
disabled = true

[status]
disabled = true

[shell]
disabled = true

[character]
disabled = false
